<html>
	<head>
		<title>会议历史记录</title>
		<meta charset="utf-8" />
		<link rel="stylesheet" href="../css/head.css">
		<link rel="stylesheet" href="../css/member.css" />
	</head>
	<body>
		<div class="all-content">
			<header>
			<?php include '../html/head.php' ?>
		    </header>
		    <div class="memberinfo">
		    	<h2>
		    		<a href="../index.php">return>></a>
		    	</h2>
		    	<table cellspacing="0">
		    		<caption>前端</caption>
		    		<tr>
		    			<th>ID</th>
		    			<th>name</th>
		    			<th>grade</th>
		    			<th>long-phone</th>
		    			<th>short-phone</th>
		    			<th>times</th>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>whyhjk</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    	</table>
		    	<table cellspacing="0">
		    		<caption>后台</caption>
		    		<tr>
		    			<th>ID</th>
		    			<th>name</th>
		    			<th>grade</th>
		    			<th>long-phone</th>
		    			<th>short-phone</th>
		    			<th>department</th>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>whyhjk</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    	</table>
		    	<table cellspacing="0">
		    		<caption>移动</caption>
		    		<tr>
		    			<th>ID</th>
		    			<th>name</th>
		    			<th>grade</th>
		    			<th>long-phone</th>
		    			<th>short-phone</th>
		    			<th>times</th>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>whyhjk</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    	</table>
		    	<table cellspacing="0">
		    		<caption>系统</caption>
		    		<tr>
		    			<th>ID</th>
		    			<th>name</th>
		    			<th>grade</th>
		    			<th>long-phone</th>
		    			<th>short-phone</th>
		    			<th>times</th>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>whyhjk</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>1</td>
		    		</tr>
		    	</table>
		    </div>
		    <div class="search">
		    	<p>
		    		<input type="text" placeholder="输入搜索内容" class="text">
		    		<input type="submit" value="GO" class="submit">
		    	</p>
		    </div>
		</div>
	</body>
</html>