<html>
	<head>
		<meta charset="utf-8" />
		<title>HCI成员信息</title>
		<link rel="stylesheet" href="../css/member.css" />
	</head>
	<body>
		<div class="all-content">
			<header>
			    <div class="logo">
				    <h1>HCI</h1>
				    <h2><span>@</span>SCAU</h2>
			    </div>
			    <div class="theme">
				    <h1>HCI REGISTRATION</h1>
			    </div>
		    </header>
		    <div class="memberinfo">
		    	<h2>
		    		<a href="../index.html">return>></a>
		    	</h2>
		    	<table cellspacing="0">
		    		<caption>11级成员信息</caption>
		    		<tr>
		    			<th>ID</th>
		    			<th>name</th>
		    			<th>grade</th>
		    			<th>long-phone</th>
		    			<th>short-phone</th>
		    			<th>department</th>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>whyhjk</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    	</table>
		    	<table cellspacing="0">
		    		<caption>12级成员信息</caption>
		    		<tr>
		    			<th>ID</th>
		    			<th>name</th>
		    			<th>grade</th>
		    			<th>long-phone</th>
		    			<th>short-phone</th>
		    			<th>department</th>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>whyhjk</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    	</table>
		    	<table cellspacing="0">
		    		<caption>13级成员信息</caption>
		    		<tr>
		    			<th>ID</th>
		    			<th>name</th>
		    			<th>grade</th>
		    			<th>long-phone</th>
		    			<th>short-phone</th>
		    			<th>department</th>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>why</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    		<tr>
		    			<td>1</td>
		    			<td>whyhjk</td>
		    			<td>11</td>
		    			<td>18826495181</td>
		    			<td>645181</td>
		    			<td>前端</td>
		    		</tr>
		    	</table>
		    </div>
		    <div class="search">
		    	<p>
		    		<input type="text" placeholder="输入搜索内容" class="text">
		    		<input type="submit" value="GO" class="submit">
		    	</p>
		    </div>
		</div>
	</body>
</html>